from alpine
expose 3000
run apk add git nodejs npm bash curl zip
run git clone https://github.com/YahyaOukharta/Coronavirus-dashboard.git /corona
COPY setup.sh /corona/setup.sh
WORKDIR /corona/
run npm install

ENTRYPOINT ["bash","setup.sh"]